echo /p You will now delete all built files:
del /S *.pbi
del /S *.cout
del /S *.browse
del /S *.o
del /S *.pbd
del /S *.map
del /S *.lst
del /S *.srec
del /S *.out
del /S *.wsdt
del /S *.B34185
del /S *.htm
del /S *.uvopt
del /S *.dep
del /S *.sim
del /S *.jlink
del /S *.Debug.cspy.bat
del /S *.Debug.cspy.bat
del /S *.dni
del /S *.dbgdt
del /S *.wspos
del /S *.crf
del /S *.d
del /S *.i
del /S *.bak
del /S *.axf
del /S *.lnp
